<a href="https://colab.research.google.com/github/dggasque/DS-Unit-1-Build/blob/master/premium_cost.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
#import tools from library
from google.colab import files

#upload car.data from local machine
uploaded = files.upload()

Saving gz_2010_us_040_00_5m.json to gz_2010_us_040_00_5m.json

In [0]:
import pandas as pd
import plotly.offline as py
import plotly.graph_objects as go

plus_one = pd.read_csv('Prem_Cost_Employee_plus_One.csv', skiprows=2, skipfooter=14, engine='python')
family = pd.read_csv('Prem_Cost_Family.csv', skiprows=2, skipfooter=12, engine='python')
single = pd.read_csv('Prem_Cost_Single_Employee.csv', skiprows=2, skipfooter=12, engine='python')

In [11]:
print(plus_one.shape)
plus_one.head()

(52, 19)

        Location  ...  2018__Total Annual Premium
0  United States  ...                       13425
1        Alabama  ...                       12307
2         Alaska  ...                       16082
3        Arizona  ...                       12784
4       Arkansas  ...                       11854

[5 rows x 19 columns]

In [18]:
print(family.shape)
family.head()

(52, 19)

        Location  ...  2018__Total Annual Premium
0  United States  ...                       19565
1        Alabama  ...                       18001
2         Alaska  ...                       21468
3        Arizona  ...                       18875
4       Arkansas  ...                       17995

[5 rows x 19 columns]

In [23]:
single.head()

        Location  ...  2018__Total Annual Premium
0  United States  ...                        6715
1        Alabama  ...                        6089
2         Alaska  ...                        8432
3        Arizona  ...                        6229
4       Arkansas  ...                        5974

[5 rows x 19 columns]

In [0]:
states = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DC", "DE", "FL", "GA", 
          "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", 
          "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", 
          "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", 
          "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"]

In [30]:
family_1 = family.drop(labels=[0])
family_1['code'] = states
family_1.head()

     Location  2013__Employee Contribution  ...  2018__Total Annual Premium  code
1     Alabama                         3791  ...                       18001    AL
2      Alaska                         4759  ...                       21468    AK
3     Arizona                         4774  ...                       18875    AZ
4    Arkansas                         3951  ...                       17995    AR
5  California                         4518  ...                       19567    CA

[5 rows x 20 columns]

In [48]:
fig1 = go.Figure(data=go.Choropleth(
    locations=family_1['code'],
    z = family_1['2018__Employer Contribution'].astype(float),
    locationmode = 'USA-states',
    colorscale = 'Blues'
))

fig1.update_layout(
    title_text = 'Average Premium Cost Paid by Employers For Family Plans',
    geo_scope='usa'
)

fig1.show()

In [50]:
py.offline.plot(fig1, filename='employer_family.html')

'employer_family.html'

In [34]:
plus_one_1 = plus_one.drop(labels=[0])
plus_one_1['code'] = states
plus_one_1.head()

     Location  2013__Employee Contribution  ...  2018__Total Annual Premium  code
1     Alabama                         2989  ...                       12307    AL
2      Alaska                         3043  ...                       16082    AK
3     Arizona                         3205  ...                       12784    AZ
4    Arkansas                         2700  ...                       11854    AR
5  California                         3007  ...                       13236    CA

[5 rows x 20 columns]

In [37]:
fig2 = go.Figure(data=go.Choropleth(
    locations=plus_one_1['code'],
    z = plus_one_1['2018__Employer Contribution'].astype(float),
    locationmode = 'USA-states',
    colorscale = 'Blues'
))

fig2.update_layout(
    title_text = 'Average Premium Cost Paid by Employers For Employee Plus One Plans',
    geo_scope='usa'
)

fig2.show()

In [39]:
single_1 = single.drop(labels=[0])
single_1['code'] = states
single_1.head()

     Location  2013__Employee Contribution  ...  2018__Total Annual Premium  code
1     Alabama                         1379  ...                        6089    AL
2      Alaska                         1078  ...                        8432    AK
3     Arizona                         1078  ...                        6229    AZ
4    Arkansas                          956  ...                        5974    AR
5  California                         1091  ...                        6542    CA

[5 rows x 20 columns]

In [41]:
fig = go.Figure(data=go.Choropleth(
    locations=single_1['code'],
    z = single_1['2018__Employer Contribution'].astype(float),
    locationmode = 'USA-states',
    colorscale = 'Blues'
))

fig.update_layout(
    title_text = 'Average Premium Cost Paid by Employers For Single Employee Plans',
    geo_scope='usa'
)

fig.show()